# Introduction to `Pandas`

Before anything, we need to import the library

In [0]:
# upgrade pandas from 0.2x to 1.x
! pip install pandas --upgrade

In [0]:
import pandas as pd
pd.__version__

'1.0.1'

## Load Data

And then, you usually load a dataset. There are mnay options for doing so:

 - `read_pickle()`
 - `read_csv()`
 - `read_excel()`
 - `read_json()`
 - `read_html()`
 - `read_feather()`
 - `read_sql()`
 - `read_gbq()`
 - *and more...*

In [0]:
filepath = 'https://raw.githubusercontent.com/aaronmcdaid/P2---Data-Analytics-With-Python/master/Berlin/WS%202019/5.%20Datasets/dataset_mountains/countries%20of%20the%20world.csv'
df = pd.read_csv(filepath_or_buffer = filepath).iloc[:,1:]

### Great, now how can we see what's inside the `df`?

In [0]:
df.head(3)

       Country                Region  ...  Industry  Service
0  Afghanistan  ASIA (EX. NEAR EAST)  ...     0.240    0.380
1      Albania        EASTERN EUROPE  ...     0.188    0.579
2      Algeria       NORTHERN AFRICA  ...     0.600    0.298

[3 rows x 20 columns]

In [0]:
df.tail(3)

      Country              Region  Population  ...  Agriculture  Industry  Service
224     Yemen           NEAR EAST    21456188  ...        0.135     0.472    0.393
225    Zambia  SUB-SAHARAN AFRICA    11502010  ...        0.220     0.290    0.489
226  Zimbabwe  SUB-SAHARAN AFRICA    12236805  ...        0.179     0.243    0.579

[3 rows x 20 columns]

In [0]:
df.sample(3)

         Country          Region  Population  ...  Agriculture  Industry  Service
74    Gaza Strip       NEAR EAST     1428757  ...        0.030     0.283    0.687
196  Switzerland  WESTERN EUROPE     7523934  ...        0.015     0.340    0.645
209       Tuvalu         OCEANIA       11810  ...        0.166     0.272    0.562

[3 rows x 20 columns]

## Common `attributes`

Now that we saw how to load a `Pandas` `DataFrame`, let's take a look at attributes.


*   **Attributes** return information about the object. Deep dive into what is the object that we have created
*   **Attributes** do not modify an object

If you type `df.` and press `tab` you will see a list of Attributes and Methods available for object.

*   Attributes does not require parenthesis at the end to be executed
*   Let's look at some example of attributes that you can check. 

For more example of attributes, please look at the  [Pandas documentation](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html#Attributes)

1a. `df.shape` returns a `tuple` of the number of rows and columns in your `df`

In [0]:
df.shape

(227, 20)

1b. `df.size` shows how many elemeents are inside the `df`

In [0]:
df.size

4540

2. `df.values` returns all the values similarly ordered as you would find in your object but as a type `numpy.ndarray`. It does not modify the data is only gives you access to this part of the obect.

In [0]:
import numpy as np

In [0]:
np.random.rand(5, 3)

array([[0.56244052, 0.2923584 , 0.97925841],
       [0.24759254, 0.43148538, 0.13090063],
       [0.52954142, 0.70794859, 0.21468086],
       [0.03134254, 0.01053534, 0.12584425],
       [0.45422229, 0.64040121, 0.16177232]])

In [0]:
df.values

array([['Afghanistan', 'ASIA (EX. NEAR EAST)', 31056997, ..., 0.38, 0.24,
        0.38],
       ['Albania', 'EASTERN EUROPE', 3581655, ..., 0.232, 0.188, 0.579],
       ['Algeria', 'NORTHERN AFRICA', 32930091, ..., 0.101, 0.6, 0.298],
       ...,
       ['Yemen', 'NEAR EAST', 21456188, ..., 0.135, 0.472, 0.393],
       ['Zambia', 'SUB-SAHARAN AFRICA', 11502010, ..., 0.22, 0.29, 0.489],
       ['Zimbabwe', 'SUB-SAHARAN AFRICA', 12236805, ..., 0.179, 0.243,
        0.579]], dtype=object)

In [0]:
type(df.Population.values)

numpy.ndarray

2. `df.index` returns the index of your `DataFrame`

It gives you a result a bit different from what we had previously with the values. It returns a `RangeIndex` object that tells you where the index start and end and what is the step between two indexes

In [0]:
df.index

RangeIndex(start=0, stop=227, step=1)

In [0]:
df.index.tolist()[:10] # first 10 items of index

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

3. `df.columns` returns the columns of the `DataFrame`

In [0]:
df.columns

Index(['Country', 'Region', 'Population', 'Area (sq. mi.)',
       'Pop. Density (per sq. mi.)', 'Coastline (coast/area ratio)',
       'Net migration', 'Infant mortality (per 1000 births)',
       'GDP ($ per capita)', 'Literacy (%)', 'Phones (per 1000)', 'Arable (%)',
       'Crops (%)', 'Other (%)', 'Climate', 'Birthrate', 'Deathrate',
       'Agriculture', 'Industry', 'Service'],
      dtype='object')

4. `df.axes` returns both the `index` and the `columns` of the `DataFrame`

In [0]:
df.axes

[RangeIndex(start=0, stop=227, step=1),
 Index(['Country', 'Region', 'Population', 'Area (sq. mi.)',
        'Pop. Density (per sq. mi.)', 'Coastline (coast/area ratio)',
        'Net migration', 'Infant mortality (per 1000 births)',
        'GDP ($ per capita)', 'Literacy (%)', 'Phones (per 1000)', 'Arable (%)',
        'Crops (%)', 'Other (%)', 'Climate', 'Birthrate', 'Deathrate',
        'Agriculture', 'Industry', 'Service'],
       dtype='object')]

5. `df.dtypes` gives you the data type of each column in your `DataFrame`. When using `.read_csv()` these are infered by `pandas` when your data is loaded. Strings are listed as `object`.

In [0]:
df.dtypes

Country                                object
Region                                 object
Population                              int64
Area (sq. mi.)                          int64
Pop. Density (per sq. mi.)            float64
Coastline (coast/area ratio)          float64
Net migration                         float64
Infant mortality (per 1000 births)    float64
GDP ($ per capita)                    float64
Literacy (%)                          float64
Phones (per 1000)                     float64
Arable (%)                            float64
Crops (%)                             float64
Other (%)                             float64
Climate                               float64
Birthrate                             float64
Deathrate                             float64
Agriculture                           float64
Industry                              float64
Service                               float64
dtype: object

## Common `methods`

Methods **do** apply a modification to the data. Examples of what you can do include: 

*   Adding values
*   Removing values
*   Ordering it

**Methods require parenthesis at the end**.

Let's apply some mathematical methods to try to get a sense of what a method is:


*   **Sum** : sums the values inside the serie together
*   **Product** : multiply all the values of the serie together
*   **Mean** : returns the mean of the serie

Of course these three methods here makes sense for numerical data and not string data.

In [0]:
# example of function
def add(number1, number2):
  sum_ = number1 + number2
  return sum_

In [0]:
add(3, 1)

4

In [0]:
# create a new DataFrame with only numerical data (non-string)
numerical = df[df.dtypes[df.dtypes != object].index.tolist()]

In [0]:
numerical.head()

   Population  Area (sq. mi.)  ...  Industry  Service
0    31056997          647500  ...     0.240    0.380
1     3581655           28748  ...     0.188    0.579
2    32930091         2381740  ...     0.600    0.298
3       57794             199  ...       NaN      NaN
4       71201             468  ...       NaN      NaN

[5 rows x 18 columns]

In [0]:
numerical.sum()

Population                            6.524045e+09
Area (sq. mi.)                        1.357975e+08
Pop. Density (per sq. mi.)            8.604370e+04
Coastline (coast/area ratio)          4.804530e+03
Net migration                         8.540000e+00
Infant mortality (per 1000 births)    7.953560e+03
GDP ($ per capita)                    2.189900e+06
Literacy (%)                          1.731320e+04
Phones (per 1000)                     5.264170e+04
Arable (%)                            3.104350e+03
Crops (%)                             1.026950e+03
Other (%)                             1.836862e+04
Climate                               4.385000e+02
Birthrate                             4.953700e+03
Deathrate                             2.060820e+03
Agriculture                           3.197900e+01
Industry                              5.965200e+01
Service                               1.198400e+02
dtype: float64

In [0]:
numerical.product()

/usr/local/lib/python3.6/dist-packages/numpy/core/_methods.py:42: RuntimeWarning: overflow encountered in reduce
  return umr_prod(a, axis, dtype, out, keepdims, initial, where)

Population                                      inf
Area (sq. mi.)                                  inf
Pop. Density (per sq. mi.)             0.000000e+00
Coastline (coast/area ratio)           0.000000e+00
Net migration                          0.000000e+00
Infant mortality (per 1000 births)    2.781310e+296
GDP ($ per capita)                              inf
Literacy (%)                                    inf
Phones (per 1000)                               inf
Arable (%)                             0.000000e+00
Crops (%)                              0.000000e+00
Other (%)                                       inf
Climate                                3.396720e+62
Birthrate                             7.716958e+288
Deathrate                             3.904596e+203
Agriculture                            0.000000e+00
Industry                              2.014051e-128
Service                                4.219138e-58
dtype: float64

In [0]:
numerical.mean()

Population                            2.874028e+07
Area (sq. mi.)                        5.982270e+05
Pop. Density (per sq. mi.)            3.790471e+02
Coastline (coast/area ratio)          2.116533e+01
Net migration                         3.812500e-02
Infant mortality (per 1000 births)    3.550696e+01
GDP ($ per capita)                    9.689823e+03
Literacy (%)                          8.283828e+01
Phones (per 1000)                     2.360614e+02
Arable (%)                            1.379711e+01
Crops (%)                             4.564222e+00
Other (%)                             8.163831e+01
Climate                               2.139024e+00
Birthrate                             2.211473e+01
Deathrate                             9.241345e+00
Agriculture                           1.508443e-01
Industry                              2.827109e-01
Service                               5.652830e-01
dtype: float64

In [0]:
numerical.max()

Population                            1.313974e+09
Area (sq. mi.)                        1.707520e+07
Pop. Density (per sq. mi.)            1.627150e+04
Coastline (coast/area ratio)          8.706600e+02
Net migration                         2.306000e+01
Infant mortality (per 1000 births)    1.911900e+02
GDP ($ per capita)                    5.510000e+04
Literacy (%)                          1.000000e+02
Phones (per 1000)                     1.035600e+03
Arable (%)                            6.211000e+01
Crops (%)                             5.068000e+01
Other (%)                             1.000000e+02
Climate                               4.000000e+00
Birthrate                             5.073000e+01
Deathrate                             2.974000e+01
Agriculture                           7.690000e-01
Industry                              9.060000e-01
Service                               9.540000e-01
dtype: float64

In [0]:
numerical.min()

Population                            7026.000
Area (sq. mi.)                           2.000
Pop. Density (per sq. mi.)               0.000
Coastline (coast/area ratio)             0.000
Net migration                          -20.990
Infant mortality (per 1000 births)       2.290
GDP ($ per capita)                     500.000
Literacy (%)                            17.600
Phones (per 1000)                        0.200
Arable (%)                               0.000
Crops (%)                                0.000
Other (%)                               33.330
Climate                                  1.000
Birthrate                                7.290
Deathrate                                2.290
Agriculture                              0.000
Industry                                 0.020
Service                                  0.062
dtype: float64

In [0]:
numerical.describe()

         Population  Area (sq. mi.)  ...    Industry     Service
count  2.270000e+02    2.270000e+02  ...  211.000000  212.000000
mean   2.874028e+07    5.982270e+05  ...    0.282711    0.565283
std    1.178913e+08    1.790282e+06  ...    0.138272    0.165841
min    7.026000e+03    2.000000e+00  ...    0.020000    0.062000
25%    4.376240e+05    4.647500e+03  ...    0.193000    0.429250
50%    4.786994e+06    8.660000e+04  ...    0.272000    0.571000
75%    1.749777e+07    4.418110e+05  ...    0.341000    0.678500
max    1.313974e+09    1.707520e+07  ...    0.906000    0.954000

[8 rows x 18 columns]

## `Series`

Although this is helpful, most of the time you just want to look at a single column, for that you'll use what is called a `Series`, which is basically a single row or column.

There are two different ways to create a `Series` from a `DataFrame`:

1. **Index Operator**, with brackets `[]`:

In [0]:
df['Population']

0      31056997
1       3581655
2      32930091
3         57794
4         71201
         ...
222     2460492
223      273008
224    21456188
225    11502010
226    12236805
Name: Population, Length: 227, dtype: int64

In [0]:
# works with spaces and special characters
df['GDP ($ per capita)']

0        700.0
1       4500.0
2       6000.0
3       8000.0
4      19000.0
        ...
222      800.0
223        NaN
224      800.0
225      800.0
226     1900.0
Name: GDP ($ per capita), Length: 227, dtype: float64

2. **Attribute Operator**, with dot `.`:

In [0]:
# only works with single words
df.Population

0      31056997
1       3581655
2      32930091
3         57794
4         71201
         ...
222     2460492
223      273008
224    21456188
225    11502010
226    12236805
Name: Population, Length: 227, dtype: int64

### Exercise:

Compute the compute the `median`, `max`, `min`, `std`, `sum` for:
 - 1. `Area (sq. mi.)`
 - 2. `Population`

In [0]:
print(df['GDP ($ per capita)'].median())
print(df['GDP ($ per capita)'].max())
print(df['GDP ($ per capita)'].min())
print(df['GDP ($ per capita)'].std())
print(df['GDP ($ per capita)'].sum())

5550.0
55100.0
500.0
10049.138513197227
2189900.0

In [0]:
print(df['Population'].median())
print(df['Population'].max())
print(df['Population'].min())
print(df['Population'].std())
print(df['Population'].sum())

4786994.0
1313973713
7026
117891326.54347652
6524044551

**Since it's much easier to work without spaces and special characters (and you'll likely be typing the column names a lot), it is common practice to clean them up into something nicer to work with**:

In [0]:
# renaming columns, you need to write ALL columns and it NEEDS to be in order
df.columns =  [
    'country', 'region', 'population', 'area', 'pop_density', 'coastline', 'net_migration',
    'infant_mortality', 'gdp_per_capita', 'literacy', 'phones', 'arable', 'crops', 'other',
    'climate', 'birthrate', 'deathrate', 'agriculture', 'industry', 'service'
]

In [0]:
# alternative renaming (DOES NOT have to be in order) also, this is NOT done "in place"
df.rename(columns = {'Population': 'population'}) # etc, etc

In [0]:
df.head(3)

       country                region  ...  industry  service
0  Afghanistan  ASIA (EX. NEAR EAST)  ...     0.240    0.380
1      Albania        EASTERN EUROPE  ...     0.188    0.579
2      Algeria       NORTHERN AFRICA  ...     0.600    0.298

[3 rows x 20 columns]

Now, we compute the mean, median, etc on a single column:

In [0]:
df.gdp_per_capita.mean()

9689.823008849558

### Exercise:

With the attribute operator, or dot notation, compute the `median`, `max`, `mode`, `std`, `sum` for:
 - 1. `Area (sq. mi.)`
 - 2. `Population`

In [0]:
df.area.mean()

598226.9559471365

In [0]:
df.area.median()

86600.0

### Get `Series` values based by index position

1. You can use brackets [ ] in order to access a specific row of a pandas `Series`. 
2. You can use a list of indexes in order to access specific rows of a pandas `Series`.

Let's look at an example:

In [0]:
s = df.country

In [0]:
s[-4:-2]

223    Western Sahara
224             Yemen
Name: country, dtype: object

In [0]:
s[4] # One index
s[ [5,7,8,10,1] ] # A list of indexes
# s[3:10] # an interval of indexes
# s[:30] # from the beginning to an index
# s[300:] # from an index to the end
# s[-30:] # start 30 results from the end
# s[-30:-10] # start 30 results from the end until 10 rows from the end

5                Angola
7     Antigua & Barbuda
8             Argentina
10                Aruba
1               Albania
Name: country, dtype: object

**NOTE** you can pass a list of indexes to a `Series` and it will return a brand new `Series` object with the index in the order specified by the list

**NOTE**: 
* You can use the `:` to pass an interval of indexes
*  The interval is [3,10 [ it is not inclusive. If you want the 10th index to be included in the interval you would have to pass s[3:11]

### Exercise:

1.  return a subset containing only the index of the `Series` from 10 to 50
2.  return the 150th values
3.  return the last 60 values

In [0]:
s[10:50]

10                    Aruba
11                Australia
12                  Austria
13               Azerbaijan
14            Bahamas, The
15                  Bahrain
16               Bangladesh
17                 Barbados
18                  Belarus
19                  Belgium
20                   Belize
21                    Benin
22                  Bermuda
23                   Bhutan
24                  Bolivia
25     Bosnia & Herzegovina
26                 Botswana
27                   Brazil
28       British Virgin Is.
29                   Brunei
30                 Bulgaria
31             Burkina Faso
32                    Burma
33                  Burundi
34                 Cambodia
35                 Cameroon
36                   Canada
37               Cape Verde
38           Cayman Islands
39     Central African Rep.
40                     Chad
41                    Chile
42                    China
43                 Colombia
44                  Comoros
45        Congo, Dem. Rep.
46    Congo, Repub. of the
47             Cook Islands
48               Costa Rica
49            Cote d'Ivoire
Name: country, dtype: object

In [0]:
s[151]

'Niger'

In [0]:
s[-1:]

226    Zimbabwe
Name: country, dtype: object

### Extract Series values based on index label

Let's extract another subsample of our dataset but this time we extract both the `Country` AND the `Population`. Our goal is to have the `Country` column as the index.

In [0]:
# create a new series
s = df.population
s.index = df.country

In [0]:
s.head()

country
Afghanistan       31056997
Albania            3581655
Algeria           32930091
American Samoa       57794
Andorra              71201
Name: population, dtype: int64

In [0]:
s[['Grenada', 'Germany', 'Greece']]

country
Grenada       89703
Germany    82422299
Greece     10688058
Name: population, dtype: int64

In [0]:
s[0] # calling the index still works with the integer 
s['Germany'] # but you can also call the value using the label of the column
s['Germany':'Greece'] # you can also use the `:` to get all the rows from the first name to a last name

country
Germany      82422299
Ghana        22409572
Gibraltar       27928
Greece       10688058
Name: population, dtype: int64

**NOTE** Now the interval `:` is inclusive

### Exercise:

Return slice of Japan to Latvia

In [0]:
s['Japan': 'Latvia']

country
Japan            127463611
Jersey               91084
Jordan             5906760
Kazakhstan        15233244
Kenya             34707817
Kiribati            105432
Korea, North      23113019
Korea, South      48846823
Kuwait             2418393
Kyrgyzstan         5213898
Laos               6368481
Latvia             2274735
Name: population, dtype: int64

## More Common `methods`

### `sort_values()` method

Calling the `sort_values()` method after a `Series` or `DataFrame` returns a brand new object. As you can see bellow:

*   The original object has been ordered in alphabetical order
*   The new index is messed up

In [0]:
df.sort_values('population').head()

                  country               region  ...  industry  service
174  St Pierre & Miquelon     NORTHERN AMERICA  ...       NaN      NaN
171          Saint Helena   SUB-SAHARAN AFRICA  ...       NaN      NaN
140            Montserrat  LATIN AMER. & CARIB  ...       NaN      NaN
209                Tuvalu              OCEANIA  ...     0.272    0.562
144                 Nauru              OCEANIA  ...       NaN      NaN

[5 rows x 20 columns]

### Exercise:

Using `.sort_values()` and `.head()` (do not use `.tail()`), find which **10 countries** has the lowest `Infant Mortality` and the highest `Population Density` (hint: you can modify the order of `sort_values` with the `ascending` `parameter`):

In [0]:
df.sort_values('infant_mortality').head(10)

            country                region  ...  industry  service
184       Singapore  ASIA (EX. NEAR EAST)  ...     0.339    0.661
195          Sweden        WESTERN EUROPE  ...     0.282    0.707
91        Hong Kong  ASIA (EX. NEAR EAST)  ...     0.092    0.906
103           Japan  ASIA (EX. NEAR EAST)  ...     0.258    0.725
93          Iceland        WESTERN EUROPE  ...     0.150    0.765
68          Finland        WESTERN EUROPE  ...     0.295    0.676
154          Norway        WESTERN EUROPE  ...     0.415    0.564
129           Malta        WESTERN EUROPE  ...     0.230    0.740
53   Czech Republic        EASTERN EUROPE  ...     0.393    0.573
4           Andorra        WESTERN EUROPE  ...       NaN      NaN

[10 rows x 20 columns]

In [0]:
df.sort_values('pop_density', ascending = False).head(10)

        country                region  ...  industry  service
138      Monaco        WESTERN EUROPE  ...       NaN      NaN
122       Macau  ASIA (EX. NEAR EAST)  ...     0.072    0.927
184   Singapore  ASIA (EX. NEAR EAST)  ...     0.339    0.661
91    Hong Kong  ASIA (EX. NEAR EAST)  ...     0.092    0.906
78    Gibraltar        WESTERN EUROPE  ...       NaN      NaN
74   Gaza Strip             NEAR EAST  ...     0.283    0.687
129       Malta        WESTERN EUROPE  ...     0.230    0.740
22      Bermuda      NORTHERN AMERICA  ...     0.100    0.890
127    Maldives  ASIA (EX. NEAR EAST)  ...     0.180    0.620
15      Bahrain             NEAR EAST  ...     0.387    0.608

[10 rows x 20 columns]

**NOTE**: Using the `sort_values()` method does not overwrite the object. It remains unaltered after applying it the `sort_values()` function

If you want to overwrite the object with the new values ordered there are 2 ways to do it:

1.   Assign to `df` the value `df.sort_values()`
2.   Use the `inplace` `parameter` of `.sort_values()`

In [0]:
# The two rows are two ways of doing the same thing
df = df.sort_values('population')
df.sort_values('population', inplace = True)

In [0]:
# instead of overwriting, you can also create a new df using the first syntax
new_df = df.sort_values('population')

# the second syntax (inplace = True), does the operation in place and returns None, so you CANNOT create a new df
new_df = df.sort_values('population', inplace = True) # this will not work

### `sort_index()` method

In [0]:
df.sort_index(inplace = True)
df.head()

          country                region  ...  industry  service
0     Afghanistan  ASIA (EX. NEAR EAST)  ...     0.240    0.380
1         Albania        EASTERN EUROPE  ...     0.188    0.579
2         Algeria       NORTHERN AFRICA  ...     0.600    0.298
3  American Samoa               OCEANIA  ...       NaN      NaN
4         Andorra        WESTERN EUROPE  ...       NaN      NaN

[5 rows x 20 columns]

In [0]:
df.reset_index(drop = True)

                  country                region  ...  industry  service
0    St Pierre & Miquelon      NORTHERN AMERICA  ...       NaN      NaN
1            Saint Helena    SUB-SAHARAN AFRICA  ...       NaN      NaN
2              Montserrat   LATIN AMER. & CARIB  ...       NaN      NaN
3                  Tuvalu               OCEANIA  ...     0.272    0.562
4                   Nauru               OCEANIA  ...       NaN      NaN
..                    ...                   ...  ...       ...      ...
222                Brazil   LATIN AMER. & CARIB  ...     0.400    0.516
223             Indonesia  ASIA (EX. NEAR EAST)  ...     0.458    0.408
224         United States      NORTHERN AMERICA  ...     0.204    0.787
225                 India  ASIA (EX. NEAR EAST)  ...     0.276    0.538
226                 China  ASIA (EX. NEAR EAST)  ...     0.473    0.403

[227 rows x 20 columns]

### Exercise:

Using the `sort_index()` or the `sort_values()` methods:

1.   Write a script that overwrite `df` and returns the `df` with index sorted in the descending order

In [0]:
df = df.sort_values('coastline')

In [0]:
df.head(3)

              country                region  ...  industry  service
0         Afghanistan  ASIA (EX. NEAR EAST)  ...     0.240    0.380
40               Chad    SUB-SAHARAN AFRICA  ...     0.259    0.406
45  Congo, Dem. Rep.     SUB-SAHARAN AFRICA  ...     0.110    0.340

[3 rows x 20 columns]

In [0]:
# revert sorting
df = df.sort_index()

In [0]:
df.head(3)

       country                region  ...  industry  service
0  Afghanistan  ASIA (EX. NEAR EAST)  ...     0.240    0.380
1      Albania        EASTERN EUROPE  ...     0.188    0.579
2      Algeria       NORTHERN AFRICA  ...     0.600    0.298

[3 rows x 20 columns]

# **STOPPED HERE**: Monday, March 2nd

In [0]:
# reload data
filepath = 'https://raw.githubusercontent.com/aaronmcdaid/P2---Data-Analytics-With-Python/master/Berlin/WS%202019/5.%20Datasets/dataset_mountains/countries%20of%20the%20world.csv'
df = pd.read_csv(filepath_or_buffer = filepath).iloc[:,1:]

# rename cols
df.columns =  [
    'country', 'region', 'population', 'area', 'pop_density', 'coastline', 'net_migration',
    'infant_mortality', 'gdp_per_capita', 'literacy', 'phones', 'arable', 'crops', 'other',
    'climate', 'birthrate', 'deathrate', 'agriculture', 'industry', 'service'
]

In [0]:
df.head()

          country                region  ...  industry  service
0     Afghanistan  ASIA (EX. NEAR EAST)  ...     0.240    0.380
1         Albania        EASTERN EUROPE  ...     0.188    0.579
2         Algeria       NORTHERN AFRICA  ...     0.600    0.298
3  American Samoa               OCEANIA  ...       NaN      NaN
4         Andorra        WESTERN EUROPE  ...       NaN      NaN

[5 rows x 20 columns]

### `idxmax()` & `idxmin()` methods

These methods allow you to return the index of the largest value of your `Series` or of the lowest value of your `Series`.

Let's take the `agriculture` colum

In [0]:
s = df.agriculture
s.index = df.country

In [0]:
s.idxmax()

'Liberia'

In [0]:
s['Liberia']

0.769

In [0]:
s[s.idxmax()]

0.769

In [0]:
s.idxmin()

'Singapore'

### Exercise:

1. Create a new `Series` that uses `Region` for the index and `Population Density` for the data.
2. Use `idxmin()` and `idxmax()` to find the region with the lowest and highest population density.

In [0]:
# TODO

### `value_counts()` method

`value_counts()` enable you to count how many time a given value occur in a `Series`

In [0]:
df.region.value_counts()

SUB-SAHARAN AFRICA      51
LATIN AMER. & CARIB     45
WESTERN EUROPE          28
ASIA (EX. NEAR EAST)    28
OCEANIA                 21
NEAR EAST               16
EASTERN EUROPE          12
C.W. OF IND. STATES     12
NORTHERN AFRICA          6
NORTHERN AMERICA         5
BALTICS                  3
Name: region, dtype: int64

### `apply()` method

The `apply()` method enables you to provide a custom function not necessarily already implemented by Pandas to your Series. 

You can both apply `predefined function` and `anonymous function (lambda)` generally much more basic to the `apply()` method

In [0]:
df.pop_density.describe()

count      227.000000
mean       379.047137
std       1660.185825
min          0.000000
25%         29.150000
50%         78.800000
75%        190.150000
max      16271.500000
Name: pop_density, dtype: float64

In [0]:
df.pop_density.median()

78.8

**First, let's create the function:**

In [0]:
def bin_pop_density(n):
    if n <= 29.15:                  return 'Low'
    elif n > 29.15 and n <= 190.15: return 'Medium'
    else:                           return 'High'

**And let's use the `.apply()` method along with the `value_counts()` to see how many of each category we'll get**

In [0]:
df.pop_density.apply(bin_pop_density).value_counts()

Medium    113
Low        57
High       57
Name: pop_density, dtype: int64

**But you'll notice that nothing has changed about our `DataFrame`...**

In [0]:
df.head(3)

       country                region  ...  industry  service
0  Afghanistan  ASIA (EX. NEAR EAST)  ...     0.240    0.380
1      Albania        EASTERN EUROPE  ...     0.188    0.579
2      Algeria       NORTHERN AFRICA  ...     0.600    0.298

[3 rows x 20 columns]

**If you want to add the new `feature` to the `DataFrame` you'll need to create a new column:**

In [0]:
# note, when creating a new column, you should **always** use bracket
# notation, otherwise it'll create it as an attribute (which is deprecated)
df['pop_density_bin'] = df.pop_density.apply(bin_pop_density)

In [0]:
df.pop_density_bin.value_counts()

Medium    113
Low        57
High       57
Name: pop_density_bin, dtype: int64

In [0]:
df[['country', 'pop_density_bin']].sample(10)

                  country pop_density_bin
49          Cote d'Ivoire          Medium
17               Barbados            High
78              Gibraltar            High
84              Guatemala          Medium
174  St Pierre & Miquelon             Low
199            Tajikistan          Medium
85               Guernsey            High
6                Anguilla          Medium
101                 Italy            High
196           Switzerland          Medium

You can also use an `anonymous function` known as a `lambda` function. These are useful for quick tasks that you don't want to create a new funtion for.

For example, you can convert the literacy rate to a percentage in the range of `0 to 1` rather than `0 to 100`:

In [0]:
df.literacy.apply(lambda lit: lit / 100).head()

0    0.360
1    0.865
2    0.700
3    0.970
4    1.000
Name: literacy, dtype: float64

### Exercise:

1. Create a new column called `gdp_per_capita_quartiles` that creates bins for the `First Quartile`, `Second Quartile`, `Third Quartile`, `Fourth Quartile` for `GDP per Capita`

In [0]:
# TODO

### `map()` method

The map method allows you to map the value of a dictionnary to a dataframe. Let say you would want to change the values of the `Sex` column from female --> `woman` and `Male` to `man`

In [0]:
new_regions = {
    'ASIA (EX. NEAR EAST)': 'Asia',
    'EASTERN EUROPE': 'E. Europe',
    'NORTHERN AFRICA': 'N. Africa',
    'OCEANIA': 'Oceania',
    'WESTERN EUROPE': 'W. Europe',
    'SUB-SAHARAN AFRICA': 'Sub-Saharan Africa',
    'LATIN AMER. & CARIB': 'Latin America & Caribbean',
    'C.W. OF IND. STATES': 'CIS',
    'NEAR EAST': 'Near East',
    'NORTHERN AMERICA': 'N. America',
    'BALTICS': 'Baltics'
}

In [0]:
df.region.map(new_regions).head()

0         Asia
1    E. Europe
2    N. Africa
3      Oceania
4    W. Europe
Name: region, dtype: object

In [0]:
df['region_simplified'] = df.region.map(new_regions)

In [0]:
df.head(3)

       country                region  ...  pop_density_bin  region_simplified
0  Afghanistan  ASIA (EX. NEAR EAST)  ...           Medium               Asia
1      Albania        EASTERN EUROPE  ...           Medium          E. Europe
2      Algeria       NORTHERN AFRICA  ...              Low          N. Africa

[3 rows x 22 columns]

**Instead of creating a new column, you can also replace a column, simply by overwriting it with the same syntax**

In [0]:
df['region'] = df.region.map(new_regions)
df.head(3)

       country     region  ...  pop_density_bin  region_simplified
0  Afghanistan       Asia  ...           Medium               Asia
1      Albania  E. Europe  ...           Medium          E. Europe
2      Algeria  N. Africa  ...              Low          N. Africa

[3 rows x 22 columns]

**But now, you have two `region` columns so you'll want to get rid of the other. You can do that with one of two ways:**

 - drop and save as the same object
 - drop in-place

In [0]:
df.drop('region_simplified', axis = 1).head(3) # df = df.drop('region_simplified', axis = 1) to save change

       country     region  population  ...  industry  service  pop_density_bin
0  Afghanistan       Asia    31056997  ...     0.240    0.380           Medium
1      Albania  E. Europe     3581655  ...     0.188    0.579           Medium
2      Algeria  N. Africa    32930091  ...     0.600    0.298              Low

[3 rows x 21 columns]

In [0]:
df.drop('region_simplified', axis = 1, inplace = True)
df.head(3)

       country     region  population  ...  industry  service  pop_density_bin
0  Afghanistan       Asia    31056997  ...     0.240    0.380           Medium
1      Albania  E. Europe     3581655  ...     0.188    0.579           Medium
2      Algeria  N. Africa    32930091  ...     0.600    0.298              Low

[3 rows x 21 columns]

### Exercise:

Using `map()`, create a new column called `is_europe` (only applies to two regions, `E. Europe` and `W.Europe`). These values should be type `boolean`.

In [0]:
df.region.unique().tolist()

['Asia',
 'E. Europe',
 'N. Africa',
 'Oceania',
 'W. Europe',
 'Sub-Saharan Africa',
 'Latin America & Caribbean',
 'CIS',
 'Near East',
 'N. America',
 'Baltics']

In [0]:
# finish building the dict
is_europe_map = {
    'Asia': False,
    'E.Europe': True,
    # continue
}

In [0]:
# TODO

## Save Data to Disk

Now that we've made a lot of changes to the original data, we'll want to save our progress so that we don't have to run the notebook from scratch each time. Pandas makes this extremely easy, just as with the `read_X()` methods, there are `to_X()` methods.

But first, let's make a new folder to save all of our progress:

In [0]:
! mkdir progress

In [0]:
! ls

progress  sample_data

**Now we just specify the filepath with the new file name**

In [0]:
df.to_csv('progress/countries_v2.csv', index = False)

**And now we can load the new file just as before:**

In [0]:
df = pd.read_csv('progress/countries_v2.csv')

While `csv` is a good format for tabular data because you can open it in more traditional applications such as Excel, you might lose some of your data types and other pandas-related information.

For example, let's see what happens we set our bin categories as a `categorical` data type:

In [0]:
df['pop_density_bin'] = df.pop_density_bin.astype('category')

In [0]:
df.pop_density_bin.dtype

CategoricalDtype(categories=['High', 'Low', 'Medium'], ordered=False)

In [0]:
df.to_csv('progress/countries_v3.csv', index = False)

In [0]:
df = pd.read_csv('progress/countries_v3.csv')

In [0]:
df.pop_density_bin.dtype

dtype('O')

**An easy way to save all of our data types would be to export it instead as a `pickle` file, which is a data format that can save nearly any python object**

In [0]:
df['pop_density_bin'] = df.pop_density_bin.astype('category')
df.pop_density_bin.dtype

CategoricalDtype(categories=['High', 'Low', 'Medium'], ordered=False)

In [0]:
df.to_pickle('progress/countries_v3.pkl')

In [0]:
df = pd.read_pickle('progress/countries_v3.pkl')
try:    df.drop('Unnamed: 0', 1, inplace = True)
except: pass

In [0]:
df.pop_density_bin.dtype

CategoricalDtype(categories=['High', 'Low', 'Medium'], ordered=False)

## Filtering Data

Filtering for a specific subset of data is a very common task and you won't always want to set the slice manually as before.

### Operators for data selection

**There are four main types of operators that we can use to select data in a `DataFrame`:**

* attribute operator
* index operator
* loc operator
* iloc operator

In [0]:
df.head(3)

       country     region  population  ...  industry  service  pop_density_bin
0  Afghanistan       Asia    31056997  ...     0.240    0.380           Medium
1      Albania  E. Europe     3581655  ...     0.188    0.579           Medium
2      Algeria  N. Africa    32930091  ...     0.600    0.298              Low

[3 rows x 21 columns]

**Select multiple columns by passing in a list with Index Operator (bracket `[]` notation)**

In [0]:
cols_to_select = ['country', 'birthrate', 'deathrate']

In [0]:
df[cols_to_select].sample(5)

            country  birthrate  deathrate
213  United Kingdom      10.71      10.13
223  Western Sahara        NaN        NaN
4           Andorra       8.71       6.25
115         Lebanon      18.52       6.21
179    Saudi Arabia      29.34       2.58

**Note**: you don't have to create a list in memory in order to filter the data:

In [0]:
df[['country', 'birthrate', 'deathrate']].sample(5)

                  country  birthrate  deathrate
193              Suriname      18.02       7.27
22                Bermuda      11.40       7.74
53         Czech Republic       9.02      10.59
88                 Guyana      18.28       8.28
174  St Pierre & Miquelon      13.52       6.83

### Exercise:

Create a new df that selects the following columns:
 - Country
 - Literacy
 - Service
 - Population Density Bins

In [0]:
# TODO

### `loc` & `iloc`

`loc` and `iloc` are very similar, with the main difference being that `iloc` selects the **`i`ndex `loc`ation**.

In [0]:
df.index = df.country

In [0]:
df.head(3)

                 country     region  ...  service  pop_density_bin
country                              ...
Afghanistan  Afghanistan       Asia  ...    0.380           Medium
Albania          Albania  E. Europe  ...    0.579           Medium
Algeria          Algeria  N. Africa  ...    0.298              Low

[3 rows x 21 columns]

In [0]:
df.loc['Germany']

country               Germany
region              W. Europe
population           82422299
area                   357021
pop_density             230.9
coastline                0.67
net_migration            2.18
infant_mortality         4.16
gdp_per_capita          27600
literacy                   99
phones                  667.9
arable                  33.85
crops                    0.59
other                   65.56
climate                     3
birthrate                8.25
deathrate               10.62
agriculture             0.009
industry                0.296
service                 0.695
pop_density_bin          High
Name: Germany, dtype: object

In [0]:
df.iloc[76]

country               Germany
region              W. Europe
population           82422299
area                   357021
pop_density             230.9
coastline                0.67
net_migration            2.18
infant_mortality         4.16
gdp_per_capita          27600
literacy                   99
phones                  667.9
arable                  33.85
crops                    0.59
other                   65.56
climate                     3
birthrate                8.25
deathrate               10.62
agriculture             0.009
industry                0.296
service                 0.695
pop_density_bin          High
Name: Germany, dtype: object

**You can also select a range of rows, as with the slice**

In [0]:
df.loc['Germany':'Greenland']

             country              region  ...  service  pop_density_bin
country                                   ...
Germany      Germany           W. Europe  ...    0.695             High
Ghana          Ghana  Sub-Saharan Africa  ...    0.387           Medium
Gibraltar  Gibraltar           W. Europe  ...      NaN             High
Greece        Greece           W. Europe  ...    0.733           Medium
Greenland  Greenland          N. America  ...      NaN              Low

[5 rows x 21 columns]

In [0]:
df.iloc[76:81]

             country              region  ...  service  pop_density_bin
country                                   ...
Germany      Germany           W. Europe  ...    0.695             High
Ghana          Ghana  Sub-Saharan Africa  ...    0.387           Medium
Gibraltar  Gibraltar           W. Europe  ...      NaN             High
Greece        Greece           W. Europe  ...    0.733           Medium
Greenland  Greenland          N. America  ...      NaN              Low

[5 rows x 21 columns]

**You can also select a subset of columns**

In [0]:
df.loc['Germany':'Greenland', 'population':'coastline']

           population     area  pop_density  coastline
country
Germany      82422299   357021        230.9       0.67
Ghana        22409572   239460         93.6       0.23
Gibraltar       27928        7       3989.7     171.43
Greece       10688058   131940         81.0      10.37
Greenland       56361  2166086          0.0       2.04

In [0]:
df.iloc[76:81, 2:6]

           population     area  pop_density  coastline
country
Germany      82422299   357021        230.9       0.67
Ghana        22409572   239460         93.6       0.23
Gibraltar       27928        7       3989.7     171.43
Greece       10688058   131940         81.0      10.37
Greenland       56361  2166086          0.0       2.04

**Sometimes you want all of the rows, but only some of the columns (or vice-versa)**

You can do this with an "empty" colon, i.e. a colon with no value specified:

In [0]:
# selects all data
df.iloc[:,:]

                       country              region  ...  service  pop_density_bin
country                                             ...
Afghanistan        Afghanistan                Asia  ...    0.380           Medium
Albania                Albania           E. Europe  ...    0.579           Medium
Algeria                Algeria           N. Africa  ...    0.298              Low
American Samoa  American Samoa             Oceania  ...      NaN             High
Andorra                Andorra           W. Europe  ...      NaN           Medium
...                        ...                 ...  ...      ...              ...
West Bank            West Bank           Near East  ...    0.630             High
Western Sahara  Western Sahara           N. Africa  ...    0.400              Low
Yemen                    Yemen           Near East  ...    0.393           Medium
Zambia                  Zambia  Sub-Saharan Africa  ...    0.489              Low
Zimbabwe              Zimbabwe  Sub-Saharan Africa  ...    0.579           Medium

[227 rows x 21 columns]

In [0]:
# selects all rows, but only the last two columns
df.iloc[:,-2:]

                service pop_density_bin
country
Afghanistan       0.380          Medium
Albania           0.579          Medium
Algeria           0.298             Low
American Samoa      NaN            High
Andorra             NaN          Medium
...                 ...             ...
West Bank         0.630            High
Western Sahara    0.400             Low
Yemen             0.393          Medium
Zambia            0.489             Low
Zimbabwe          0.579          Medium

[227 rows x 2 columns]

In [0]:
# selects last two rows, and all columns
df.iloc[-2:,:]

           country              region  ...  service  pop_density_bin
country                                 ...
Zambia      Zambia  Sub-Saharan Africa  ...    0.489              Low
Zimbabwe  Zimbabwe  Sub-Saharan Africa  ...    0.579           Medium

[2 rows x 21 columns]

**And finally, you can also pass in a list of values**

In [0]:
random_country_list = df.country.sample(5).tolist()
random_country_list

['Czech Republic', 'Tunisia', 'Mongolia', 'Marshall Islands', 'Brazil']

In [0]:
df.loc[random_country_list]

                           country  ... pop_density_bin
country                             ...
Czech Republic      Czech Republic  ...          Medium
Tunisia                    Tunisia  ...          Medium
Mongolia                  Mongolia  ...             Low
Marshall Islands  Marshall Islands  ...             Low
Brazil                      Brazil  ...             Low

[5 rows x 21 columns]

In [0]:
#df.loc[random_country_list, ['region', 'population', 'pop_density_bin', 'is_europe']]

In [0]:
from random import randint

In [0]:
random_idx_list = [randint(0, df.shape[0]) for _ in range(5)]
random_idx_list

[4, 48, 113, 73, 174]

In [0]:
df.iloc[random_idx_list]

                                   country  ... pop_density_bin
country                                     ...
Andorra                            Andorra  ...          Medium
Costa Rica                      Costa Rica  ...          Medium
Laos                                  Laos  ...             Low
Gambia, The                   Gambia, The   ...          Medium
St Pierre & Miquelon  St Pierre & Miquelon  ...             Low

[5 rows x 21 columns]

In [0]:
df.iloc[random_idx_list, [1, 2, -2, -1]]

                                         region  ...  pop_density_bin
country                                          ...
Andorra                               W. Europe  ...           Medium
Costa Rica            Latin America & Caribbean  ...           Medium
Laos                                       Asia  ...              Low
Gambia, The                  Sub-Saharan Africa  ...           Medium
St Pierre & Miquelon                 N. America  ...              Low

[5 rows x 4 columns]

### Exercise:

**Select subsets of data using `loc`**:

 - Indonesia to Jamaica, all columns
 - Indonesia to Jamaica, Net Migration to Literacy
 - Indonesia to Jamaica, Climate on
 
**Select subsets of data using `iloc`**:

 - Rows 200 to 215, all columns
 - Rows 200 to 215, Net Migration to Literacy
 - Rows 200 to 215, Climate on

In [0]:
# TODO

### Boolean Filtering

Sometimes you don't want to select rows based on their index or columns but based on what is inside the rows. For that there are multiple ways and one of the ways is the use the boolean selection.

**Question:** Who can tell me what is a boolean selection?

For example, let's say you want to look at all countries with more than 100 million people. That's a use case where you could use boolean selection.

In [0]:
criteria = df.population >= 1e8 & df.area > 10
criteria

NameError: ignored

**Now, let's pass the Boolean Series into the df as you would a list when selecting columns**

In [0]:
df[criteria]

                     country  ... pop_density_bin
country                       ...
Bangladesh        Bangladesh  ...            High
Brazil                Brazil  ...             Low
China                  China  ...          Medium
India                  India  ...            High
Indonesia          Indonesia  ...          Medium
Japan                  Japan  ...            High
Mexico                Mexico  ...          Medium
Nigeria              Nigeria  ...          Medium
Pakistan            Pakistan  ...            High
Russia                Russia  ...             Low
United States  United States  ...          Medium

[11 rows x 21 columns]

**You can also pass the criteria directly into the df**

In [0]:
df[df.population >= 1e8]

                     country  ... pop_density_bin
country                       ...
Bangladesh        Bangladesh  ...            High
Brazil                Brazil  ...             Low
China                  China  ...          Medium
India                  India  ...            High
Indonesia          Indonesia  ...          Medium
Japan                  Japan  ...            High
Mexico                Mexico  ...          Medium
Nigeria              Nigeria  ...          Medium
Pakistan            Pakistan  ...            High
Russia                Russia  ...             Low
United States  United States  ...          Medium

[11 rows x 21 columns]

**You can combine many conditions together by using**:
* the **&** for **intersection**
* the **|** for **union**

In [0]:
df[(df.population >= 1e8) & (df.pop_density_bin == 'Low')]

        country                     region  ...  service  pop_density_bin
country                                     ...
Brazil   Brazil  Latin America & Caribbean  ...    0.516              Low
Russia   Russia                        CIS  ...    0.575              Low

[2 rows x 21 columns]

In [0]:
df[(df.population >= 1e8) | (df.pop_density_bin == 'High')]

                       country  ... pop_density_bin
country                         ...
American Samoa  American Samoa  ...            High
Aruba                    Aruba  ...            High
Bahrain                Bahrain  ...            High
Bangladesh          Bangladesh  ...            High
Barbados              Barbados  ...            High
...                        ...  ...             ...
Tuvalu                  Tuvalu  ...            High
United Kingdom  United Kingdom  ...            High
United States    United States  ...          Medium
Vietnam                Vietnam  ...            High
West Bank            West Bank  ...            High

[64 rows x 21 columns]

### Exercise:

Filter for the folowing criteria sets (a new df for each):

 - Birthrate between 45-60%
 - Countries in regions: Asia OR Near East

In [0]:
# TODO

### More Boolean Selection

**Boolean selection with `.loc`**

The loc attributes also takes condition instead of columns or rows

In [0]:
df.loc[
    (df.population >= 1e7) & (df.pop_density_bin == 'Low'),
    'country': 'pop_density'
]

                             country  ... pop_density
country                               ...
Algeria                      Algeria  ...        13.8
Angola                        Angola  ...         9.7
Argentina                  Argentina  ...        14.4
Australia                  Australia  ...         2.6
Brazil                        Brazil  ...        22.1
Canada                        Canada  ...         3.3
Chile                          Chile  ...        21.3
Congo, Dem. Rep.   Congo, Dem. Rep.   ...        26.7
Kazakhstan                Kazakhstan  ...         5.6
Mali                            Mali  ...         9.5
Mozambique                Mozambique  ...        24.6
Niger                          Niger  ...         9.9
Peru                            Peru  ...        22.0
Russia                        Russia  ...         8.4
Saudi Arabia            Saudi Arabia  ...        13.8
Sudan                          Sudan  ...        16.5
Venezuela                  Venezuela  ...        28.2
Zambia                        Zambia  ...        15.3

[18 rows x 5 columns]

**You can also use the `~` operator to select the opposite**

In [0]:
df[~(df.pop_density_bin == 'Low')]

                             country  ... pop_density_bin
country                               ...
Afghanistan              Afghanistan  ...          Medium
Albania                      Albania  ...          Medium
American Samoa        American Samoa  ...            High
Andorra                      Andorra  ...          Medium
Anguilla                    Anguilla  ...          Medium
...                              ...  ...             ...
Virgin Islands        Virgin Islands  ...          Medium
Wallis and Futuna  Wallis and Futuna  ...          Medium
West Bank                  West Bank  ...            High
Yemen                          Yemen  ...          Medium
Zimbabwe                    Zimbabwe  ...          Medium

[170 rows x 21 columns]

In [0]:
df.region.unique().tolist()

['Asia',
 'E. Europe',
 'N. Africa',
 'Oceania',
 'W. Europe',
 'Sub-Saharan Africa',
 'Latin America & Caribbean',
 'CIS',
 'Near East',
 'N. America',
 'Baltics']

**Anything that returns a boolean can be used for boolean filtering**

In [0]:
african_regions = ['N. Africa', 'Sub-Saharan Africa']

In [0]:
df.region.isin(african_regions)

country
Afghanistan       False
Albania           False
Algeria            True
American Samoa    False
Andorra           False
                  ...
West Bank         False
Western Sahara     True
Yemen             False
Zambia             True
Zimbabwe           True
Name: region, Length: 227, dtype: bool

In [0]:
df[df.region.isin(african_regions)].sample(5)

             country              region  ...  service  pop_density_bin
country                                   ...
Libya          Libya           N. Africa  ...    0.425              Low
Morocco      Morocco           N. Africa  ...    0.426           Medium
Guinea        Guinea  Sub-Saharan Africa  ...    0.401           Medium
Swaziland  Swaziland  Sub-Saharan Africa  ...    0.366           Medium
Burundi      Burundi  Sub-Saharan Africa  ...    0.334             High

[5 rows x 21 columns]

In [0]:
df[~df.region.isin(african_regions)].sample(5)

                     country  ... pop_density_bin
country                       ...
Nicaragua          Nicaragua  ...          Medium
Macedonia          Macedonia  ...          Medium
Estonia              Estonia  ...          Medium
Vanuatu              Vanuatu  ...             Low
Liechtenstein  Liechtenstein  ...            High

[5 rows x 21 columns]

In [0]:
df.region.unique().tolist()

['Asia',
 'E. Europe',
 'N. Africa',
 'Oceania',
 'W. Europe',
 'Sub-Saharan Africa',
 'Latin America & Caribbean',
 'CIS',
 'Near East',
 'N. America',
 'Baltics']

### Exercise:

Filter a subset of data that is **NOT** in the following regions:
 - Oceania
 - Asia
 - Near East
 - CIS

In [0]:
# TODO

### `query()`

In [0]:
df.query('population > 1000000000')

        country region  population  ...  industry  service  pop_density_bin
country                             ...
China     China   Asia  1313973713  ...     0.473    0.403           Medium
India     India   Asia  1095351995  ...     0.276    0.538             High

[2 rows x 21 columns]

In [0]:
df.query('population > 1e9')

        country region  population  ...  industry  service  pop_density_bin
country                             ...
China     China   Asia  1313973713  ...     0.473    0.403           Medium
India     India   Asia  1095351995  ...     0.276    0.538             High

[2 rows x 21 columns]

### Exercise:

Query for the countries where the `Birthrate` is greater than the `Deathrate`

In [0]:
# TODO

## Build `Series` & `DataFrame` from scratch

In [0]:
import numpy as np

Sometimes you'll need to create a pandas object from scratch. You can do this pretty easily using basic python data types.

### `Series`

In [0]:
s = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9])
s

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int64

In [0]:
s = pd.Series(['Red', 'Blue', 'Green', 'Blue'], index = [10, 20, 30, 40])
s

10      Red
20     Blue
30    Green
40     Blue
dtype: object

In [0]:
data = {
    10: 'Red',
    20: 'Blue',
    30: 'Green',
    40: 'Blue',
}

In [0]:
s = pd.Series(data)
s

10      Red
20     Blue
30    Green
40     Blue
dtype: object

### `DataFrame`

**Create an empty `DataFrame`**

In [0]:
empty_df = pd.DataFrame()
empty_df.empty

True

**Create `DataFrame` with a `dictionary`**

In [0]:
data = {
    'col1': -1,                    # single value
    'col2': [100, 80, 60, 40, 20], # list of values
    'col3': range(5, 15, 2),       # iterable
    'col4': np.random.rand(5),     # numpy array
    
}

In [0]:
df = pd.DataFrame(data)
df

   col1  col2  col3      col4
0    -1   100     5  0.093569
1    -1    80     7  0.975466
2    -1    60     9  0.322903
3    -1    40    11  0.302901
4    -1    20    13  0.769461

**Create `DataFrame` with a `list`**

In [0]:
data = [
    {'color': 'red', 'size': 'large', 'quantity': 5},
    {'color': 'blue', 'size': 'medium', 'quantity': 2},
    {'color': 'blue', 'size': 'xlarge', 'quantity': 10},
    {'color': 'green', 'size': 'small', 'quantity': 8},
]

In [0]:
df = pd.DataFrame(data)
df

   color    size  quantity
0    red   large         5
1   blue  medium         2
2   blue  xlarge        10
3  green   small         8

**Create `DataFrame` with a `numpy array`**

In [0]:
data = np.random.rand(5, 3)
data

array([[0.57448753, 0.75202828, 0.76754957],
       [0.68278041, 0.68947946, 0.04343925],
       [0.91079584, 0.1515868 , 0.11208452],
       [0.72371891, 0.89000977, 0.09124232],
       [0.66194299, 0.12804695, 0.51242699]])

In [0]:
df = pd.DataFrame(data, columns = ['a', 'b', 'c'])
df

          a         b         c
0  0.574488  0.752028  0.767550
1  0.682780  0.689479  0.043439
2  0.910796  0.151587  0.112085
3  0.723719  0.890010  0.091242
4  0.661943  0.128047  0.512427

In [0]:
data = np.ones((10, 5))
data

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [0]:
df = pd.DataFrame(data, columns = [1, 2, 3, 4, 5])
df

     1    2    3    4    5
0  1.0  1.0  1.0  1.0  1.0
1  1.0  1.0  1.0  1.0  1.0
2  1.0  1.0  1.0  1.0  1.0
3  1.0  1.0  1.0  1.0  1.0
4  1.0  1.0  1.0  1.0  1.0
5  1.0  1.0  1.0  1.0  1.0
6  1.0  1.0  1.0  1.0  1.0
7  1.0  1.0  1.0  1.0  1.0
8  1.0  1.0  1.0  1.0  1.0
9  1.0  1.0  1.0  1.0  1.0

## Homework

**Dataquest Homework**:
 - https://app.dataquest.io/m/291/introduction-to-pandas/1/understanding-pandas-and-numpy
 - https://app.dataquest.io/m/381/exploring-data-with-pandas%3A-fundamentals/1/introduction-to-the-data

**Homework that will be reviewed next class**

1. Download the Titanic dataset (and load into a `DataFrame`) from: https://public.opendatasoft.com/explore/dataset/titanic-passengers/download/?format=csv&timezone=Europe/Berlin&lang=en&use_labels_for_header=true&csv_separator=%3B
2. Rename the columns so that they are easier to work with using the attribute operator (dot notation)
3. Get the count of the number of people who survived vs didn't survive
4. Get the `mode` of the passenger's class (`Pclass`)
5. Get the average fare paid for all passengers
6. Get the `sum` of the fare paid by all passengers
7. Get the `sum` of the fare paid by first class passengers only
8. Get the `median` age of all passengers
9. Get the `median` age of second and third class customers
10. Use the `apply()` method to create new column that marks a passenger `younger` if they are below mean age and `older` if they are above mean age
11. Use `map()` to change values in `Embarked` column: `C -> Cherbourg`, `Q -> Queenstown`, `S -> Southampton`
12. Save your final results to your disk as a `csv` and make sure you can reload the new file